### ISSUE TITLE
Crashes in resolutions above 1080p

### ISSUE THREAD

**Issue by hntd187** [sy1ntexx/egui-d3d11#2]
If I try and make an overlay with this it works fine if I never change my resolution to be above 1920x1080. I use 1440p for most, but it appears that any change to resolution crashes the game. 

It works just fine in 1080p, so I'd imagine something with the textures scaling, but I didn't get a chance to debug it that far yet.

**Comment by sy1ntexx** [comment]
What game did you try on? Currently I have experienced a problem that crashes the game if it's not launched from steam, must be something up with hooks but I didn't have time to investigate. Try launching the game from steam or try further debugging.

**Comment by hntd187** [comment]
It was resident evil 2 remake. I was using ultimate asi loader to be lazy and load the dll. Normally I’d have to hook dinput if I wanted to interact with the gui at all. Maybe I’m doing something wrong with injecting that I shouldn’t do. 

I’ll admit I am hardly an expert in this but how do you debug something like this? The game crashes before I can catch anything tangible but I can track something down if you are curious. 

Also, I always launch via steam if I don’t the game just never starts.

**Comment by sy1ntexx** [comment]
I don't have this game so I won't be able to check it myself. Usually problems like this I debug with x64dbg.

**Comment by hntd187** [comment]
Upon further inspection I noticed that when I obtain function pointers from the steam overlay everything works fine, but when obtaining them from dxgi they cause crashes. 

I can also obtain the dxgi fn pointers from the windows crate themselves via
```rust 
let present_fn = Interface::vtable(&swapchain).Present as usize;
let resize_fn = Interface::vtable(&swapchain).ResizeBuffers as usize;
```
those locations line up with the ones gotten from a pattern scan, but still cause things to crash. I'm going to try other games to see if it's only something specific to the resident evils or otherwise. Do you have a game you'd recommend to test on so I can lineup with something you can perhaps replicate?

**Comment by sy1ntexx** [comment]
It sounds similar to the problem I described earlier when the game crashes if launched without steam because in that case current implementation of example dll falls back to getting addresses from dxgi.dll instead of steam overlay. As for the other games, you can try testing on the crab game, it's free and doesn't have an anti-cheat. When I have more time I'll try to debug what's wrong with hooks through dxgi.dll

**Comment by sy1ntexx** [comment]
So it seems like the problem was related to hooks and not the backend itself. My hooks implementation was using rax register  which is not usually used in the function prelude but this time it was so it obviously caused some problems. The "sunshine" library was created just for the sake of example and obviously not the best solution.   Ideally you either want to use your own hooks library or some other more "trusted" library.
